spring:
  config:
    import:
      - optional:classpath:config/shared.yaml
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      chat:
        enabled: true
        options:
          model: gpt-4o
          temperature: 0.0
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small