spring:
  ai:
    ollama:
      chat:
        enabled: false
      embedding:
        enabled: false
    openai:
      api-key: ${OPENAI_API_KEY:demo}
      chat:
        enabled: true
        options:
          model: gpt-3.5-turbo
          temperature: 0.0
      embedding:
        enabled: true
        options:
          model: text-embedding-3-small